<?php

/**
 * @file
 * Module file for Time-n-Weather module.
 */

/**
 * Implements hook_menu().
 */

function timenweather_menu() {
  $items['admin/config/timenweather/settings'] = array(
    'title'             => 'Time-n-Weather configuration page',
    'description'       => 'Changing all module\'s configurations.' ,
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('timenweather_admin_settings'),
    'access arguments'  => array('administer site configuration'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'timenweather.admin.inc',
  );

  return $items;	
} 


